### PR TITLE
Request Removal of Korean Translations

### PR DESCRIPTION
**Pull request by Bhngjjb**
I did these translations as volunteer contributor i am no longer happy with my contributions and would like to delete them

#50 
about.kr.md 
roadmap.kr.md 
manifesto.kr.md 
2020-08-15-foundation-announcement.kr.md 
2020-08-18-not-affiliated-moonrabbit.kr.md 
2021-08-31-advisory-dogecoin2.kr.md

#83 
2021-11-11-transaction-broadcast.kr.md

#99 
gigawallet.kr.md 
libdogecoin.kr.md 
prologue.kr.md 
standard.kr.md 
website.kr.md

#128 
2022-01-21-update-ama.kr.md 
2022-02-24-update-ross.kr.md 
kr.toml

additionally removal of korean translation for config.toml
removal of kr from langflags.yaml

also looking to remove contributions for dogecoin .com in the following pull request https://github.com/dogecoinfoundation/dogecoin.com/pull/274

### CODE REVIEW

**Comment by qlpqlp** [comment]
> I did these translations as volunteer contributor i am no longer happy with my contributions and would like to delete them
> 
> #50 
> about.kr.md 
> roadmap.kr.md 
> manifesto.kr.md 
> 2020-08-15-foundation-announcement.kr.md 
> 2020-08-18-not-affiliated-moonrabbit.kr.md 
> 2021-08-31-advisory-dogecoin2.kr.md
> 
> #83 
> 2021-11-11-transaction-broadcast.kr.md
> 
> #99 
> gigawallet.kr.md 
> libdogecoin.kr.md 
> prologue.kr.md 
> standard.kr.md 
> website.kr.md
> 
> #128 
> 2022-01-21-update-ama.kr.md 
> 2022-02-24-update-ross.kr.md 
> kr.toml
> 
> additionally removal of korean translation for config.toml
> removal of kr from langflags.yaml

Hello :)

Any particular problem with your contribution to be reviewed by other Korean translation member?

**Comment by qlpqlp** [comment]
It has to be reviewed, it can take some time to see if dosent break anything or conflicts with pending pr.

I will ask someone to grab your translation, improve it if needed and deploy again because all the community wants more trabslations lime yours, and not to remove them 🙂

**Comment by bobdos** [comment]
Hi @Bhngjjb 

I saw those kr translations are committed by dogespacewizard, should we contact him first?

CC @qlpqlp

**Comment by bobdos** [comment]
> It has to be reviewed, it can take some time to see if dosent break anything or conflicts with pending pr.
> 
> I will ask someone to grab your translation, improve it if needed and deploy again because all the community wants more trabslations lime yours, and not to remove them 🙂

agree with @qlpqlp we shall find someone else to improve/polish the translation and redeploy them, but not remove all of them.

CC @Bhngjjb

**Review by bobdos — APPROVED** [review]
hi @Bhngjjb,

First of all, many thanks for your contribution to this project.  

1. When you first time contributed to this project, you licensed your work under the MIT license.
2. Based on the MIT license, we agree to accept your removal request on your own translation parts. 
3. We respect your hard work, and welcome you back anytime for future contributions.

Good luck.

Regards,
bobdos

**Pull request merged**
