### PR TITLE
create 2022-01-21-update-ama.zh-cn.md

### PR DESCRIPTION
**Pull request by shuferhoo**
create 2022-01-21-update-ama.zh-cn.md

### CODE REVIEW

**Comment by shuferhoo** [comment]
@bobdos

**Comment by bobdos** [comment]
hi @shuferhoo, what is your Twitter account id? 

just want to double confirm and avoid scams.

**Comment by shuferhoo** [comment]
randomwalk，the man is me，it is real.

**Comment by shuferhoo** [comment]
hi, @bobdos how can I join dogecoin foundation translate team?

**Review by bobdos — APPROVED** [review]
all good and it's ready to go.

many thanks for your contribution.

**Pull request merged**
