### PR TITLE
korean trailmap translations all files

### PR DESCRIPTION
**Pull request by dogespacewizard**
just wanted to put this pr in and commit to it and make it easier for other korean speakers to edit in their own translations

### CODE REVIEW

**Comment by bobdos** [comment]
good job, keep going. :)

**Comment by bobdos** [comment]
will you continue to translate the remaining ones?

if not, then no need to submit the un-translated ones.

**Comment by dogespacewizard** [comment]
> 

i'm going to continue to translate more/add more commits for each file, but other korean speakers can freely edit my files directly from this pr if they want

**Comment by dogespacewizard** [comment]
all finished

**Review by bobdos — APPROVED** [review]
all good. it's ready to go.

please merge.

**Pull request merged**
