### PR TITLE
fix the focusing issue of the title list

### PR DESCRIPTION
**Pull request by bobdos**

### CODE REVIEW

**Review by memetaverse — DISMISSED** [review]
fixes for focusing issue are good to go

**Comment by memetaverse** [comment]
Hi @bobdos, for [GigaWallet](https://github.com/dogecoinfoundation/foundation.dogecoin.com/blob/02e492c81610f8aba07045085f52c26ebdc6a86b/content/trailmap/gigawallet.fr.md)
In line 4, please change `type = "À propos"` to `type = "about"` then it will fix the layout issue.
The other fixes you made are ready to go 🐕

**Comment by bobdos** [comment]
> Hi @bobdos, for [GigaWallet](https://github.com/dogecoinfoundation/foundation.dogecoin.com/blob/02e492c81610f8aba07045085f52c26ebdc6a86b/content/trailmap/gigawallet.fr.md) In line 4, please change `type = "À propos"` to `type = "about"` then it will fix the layout issue. The other fixes you made are ready to go 🐕

@memetaverse 
thanks. it works, yeah.

I've submitted the changes, please review and approve them if all is good then.

**Review by memetaverse — APPROVED** [review]
all good. cheers!

**Comment by bobdos** [comment]
> all good. cheers!

thanks. :)

**Pull request merged**
